<?php
/** @var \Riskified\Decider\Block\Js $block */
?>
<?php if ($block->isEnabled() && $block->isDecoEnabled()) : ?>
    <script>
        (function (window, document) {
            var loader = function() {
                var script = document.createElement("script"), tag = document.getElementsByTagName("script")[0];
                script.src = 'https://sandboxapp.decopayments.com/be/widget/widget.js?shop_url=<?php echo $block->getShopDomain(); ?>';
                    console.log(script.src);
                tag.parentNode.insertBefore(script, tag);
            };
            window.addEventListener ? window.addEventListener("load", loader, false) : window.attachEvent("onload", loader);
        })(window, document);
    </script>
<?php endif; ?>
